services:
  recycleright:
    image: ghcr.io/phatdattran2k2/recycleright:latest
    container_name: deploy-recycleright-1
    restart: unless-stopped
    runtime: nvidia
    privileged: true
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - /home/jetson/recycleright/models:/models:ro
      - /tmp/argus_socket:/tmp/argus_socket
    environment:
      - MODEL_PATH=/models/best_fp16.engine
      - SSH_CLIENT=docker
    network_mode: host
